# This rule is not used by the project scalableinference itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants full permissions ('*') over apps.my.domain.
# This role is intended for users authorized to modify roles and bindings within the cluster,
# enabling them to delegate specific permissions to other users or groups as needed.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: scalableinference
    app.kubernetes.io/managed-by: kustomize
  name: atlas-admin-role
rules:
- apiGroups:
  - apps.my.domain
  resources:
  - atlas
  verbs:
  - '*'
- apiGroups:
  - apps.my.domain
  resources:
  - atlas/status
  verbs:
  - get
